### ISSUE TITLE
Erro no rastreamento de objetos

### ISSUE THREAD

**Issue by WiltonNunes** [ivanwhm/correios#10]
Segui o exemplo de código para rastreamento de objetos, passando os paramentos da seguinte forma:

$rastreamento = new CorreiosRastreamento('ECT', 'SRO');

mas quando executo o código ele retorna o seguinte erro:

Ocorreu um erro ao processar sua solicitação. Erro: SRO number is invalid.

Alguem poderia me ajudar?

**Comment by allantorres** [comment]
Você se importa de mandar o código completo do qual está tentando rastrear?

**Comment by GBraL** [comment]
Olá, boa tarde.

Em primeiro lugar queria parabeniza-lo pelo código. Gostei muito mas ainda não consegui faze-lo funcionar 100%.

Primeiro ele acusa o mesmo erro do colega Wilton (segue código de teste: PN450841675BR) mas quando comento a validação do número de rastreio ele vai, porém, vai MUITOOOOOO lento mas muito lento mesmo. Demora minutos até retornar e quando retorna trás parte da informação e um NOTICE com "Undefined index".

Era para ser tão lento assim mesmo?

Outra pergunta: ele só trás a primeira linha da última movimentação? Não tem como trazer toda a movimentação ou ao menos a última movimentação completa? Pois se um objeto é encaminhado eu quero saber para onde foi encaminhado e trouxe apenas que foi encaminhado a partir do local X mas não fala para onde ele foi.

Desde já obrigado.

**Comment by ivanwhm** [comment]
Olá GBraL,

O problema da mensagem "SRO number is invalid" é por causa da sigla "PN" que os correios criou recentemente. Esta sigla foi incluída na issue https://github.com/ivanwhm/correios/issues/11. Só atualizar teu código.

Em relação a lentidão, é um problema conhecido (conforme mencionado no README). Infelizmente as requisições SOAP dos Correios possuem esta lentidão (e não sei porque exatamente). Estou esperando um tempinho para converter as classes para usar cUrl, mas, sem previsão.

Em relação aos registros, podes usar o código abaixo para trazer todos os eventos de um SRO.

Traz o último eventos
$rastreamento->setResultado(Correios::RESULTADO_RASTREAMENTO_ULTIMO);

Traz todos os eventos
$rastreamento->setResultado(Correios:: RESULTADO_RASTREAMENTO_TODOS);

Precisando estamos às ordens!

**Comment by GBraL** [comment]
Obrigado Ivan, vou atualizar, mas infelizmente assim não dá para usar.

Se tiver tempo vou tentar fazer a conversão para CURL. Se o fizer envio o código para você.

Grande abraço.

**Comment by robsongomesdejesus** [comment]
Olá, eu estou com o mesmo erro, já foi corrigido?
Dei uma olhada na pastagem falando sobre a sigla 'PN' porem aqui esta atualizado e tenho o mesmo erro relatado acima
Ocorreu um erro ao processar sua solicitação. Erro: SRO number is invalid.
