### ISSUE TITLE
Nova sigla

### ISSUE THREAD

**Issue by isaaclopes** [ivanwhm/correios#11]
Ola,
Obrigado por essa classe, tem uma nova sigla de acordo os correios para https://github.com/ivanwhm/correios/blob/master/src/Sro/CorreiosSro.php#L185

'PN' => 'PAC',

**Comment by ivanwhm** [comment]
Olá Isaac, vou providenciar o ajuste assim que possível. Caso queira, podes fazer o ajuste e enviar um Pull Request que eu libero!

**Comment by ivanwhm** [comment]
Olá Isaac,
Sigla PN incluída.
https://github.com/ivanwhm/correios/commit/975e2940e3e5a4ea16029e9301d908b4414bfcea
