### ISSUE TITLE
Instalação em Laravel 5.1

### ISSUE THREAD

**Issue by edsonrodsilva** [ivanwhm/correios#12]
Olá, Estou testando o package e parece muito bom, estou tentando implementar em Laravel 5.1, pos não consegui instalar via composer. Fica exibindo a mensagem abaixo: 
[InvalidArgumentException]                                                                                                                    
  Could not find package ivan/correios at any version for your minimum-stability (stable). Check the package spelling or your minimum-stabilit y

Pode me ajudar com isto, como seria a instalação em laravel?

Valeu.

**Comment by ivanwhm** [comment]
Olá Edson, o pacote não está disponível no Composer.
Precisa baixar e instalar manualmente.
