### ISSUE TITLE
Adicionar o pacote no composer 

### ISSUE THREAD

**Issue by nicollaas94** [ivanwhm/correios#13]
Seria de grande utilidade adicionar o pacote no composer.
#12 

Workaround:

adicionar 
``    "repositories": [
        {
            "url": "https://github.com/ivanwhm/correios.git",
            "type": "git"
        }
    ],
``
no composer e executar um:
`` composer require ivan/correios:dev-master``

**Comment by ivanwhm** [comment]
A partir de hoje, o projeto está deprecado.
