### ISSUE TITLE
Código de serviço inválido (PAC e SEDEX sem contrato)

### ISSUE THREAD

**Issue by lemmks** [ivanwhm/correios#20]
Para as consultas de PAC e SEDEX sem contrato o web service dos Correios está retornando:

 "Ocorreu um erro no calculo do servico 41106 (PAC sem contrato): Codigo de servico invalido. Desde 05/05/2017 ele foi substituido pelo 04510.
Ocorreu um erro no calculo do servico 40010 (Sedex sem contrato): Codigo de servico invalido. Desde 05/05/2017 ele foi substituido pelo 04014."

**Comment by ivanwhm** [comment]
Olá
Suporte aos códigos incluídos no commit https://github.com/ivanwhm/correios/commit/4e63fcb31ebb2b495d330b03919265654a122b19

Obrigado!
