### ISSUE TITLE
Correios fora do ar

### ISSUE THREAD

**Issue by daviddgm** [ivanwhm/correios#5]
Alguém sabe dizer se nessa semana os Correios estão fora do ar para usar rastreamento ou se mudou algo que deverá ser ajustado?

**Comment by frankdors** [comment]
Estou com o mesmo problema... alguma solução alternativa?

**Comment by alexisdeza** [comment]
> ...Assim, os clientes que realizam consulta ao WebSRO por meio de integração WebService devem ser orientados a atualizar o endereço do servidor nos seus sistemas próprios:
> Endereço antigo (descontinuado): http://websro.correios.com.br/sro_bin/sroii_xml.eventos
> Endereço atual: https://webservice.correios.com.br/service/rastro/Rastro.wsdl

**Comment by frankdors** [comment]
Opa, obrigado!

Pra min está bem lento o acesso ao webservice no momento.

Achei o link da documentação:
https://github.com/pedro-teixeira/correios/pull/139#issuecomment-226487209

**Comment by daviddgm** [comment]
Olá...
É preciso atualizar a URL e alterar o acesso de curl para soap?

**Comment by alexisdeza** [comment]
@daviddgm eu fiz em soap, infelizmente eu não consegui usar

**Comment by btrazzini** [comment]
@alexisdeza Valeu pelo script, executei aqui e funcionou. Porém, quase sempre da timeout.
Alguma sugestão?

**Comment by daviddgm** [comment]
Aqui deu timeout, então baixei o Rastro.wsdl e Rastro_schema1.xsd e uso localmente...

**Comment by btrazzini** [comment]
@alexisdeza coloque `ini_set('default_socket_timeout', 1);` antes do SoapClient e veja se resolve.

**Comment by daviddgm** [comment]
Resolvi aqui, mas não ficou elegante, pois não sei acessar o namespace do XML, se alguém puder dar uma dica, mas tá funcionando.

  if (@fopen(parent::URL_CALCULADOR, 'r'))
      {
        //Inicia a consulta
        //$curl = curl_init();
        //curl_setopt($curl, CURLOPT_URL, parent::URL_RASTREADOR);
        //curl_setopt($curl, CURLOPT_RETURNTRANSFER, 1);
        //curl_setopt($curl, CURLOPT_POST, 1);
        //curl_setopt($curl, CURLOPT_POSTFIELDS, http_build_query($this->getParametros()));
        //$result = curl_exec($curl);
        //$saida = $result;
        //curl_close($curl);
        $client = new SoapClient("../classes/Rastro.wsdl", array('trace' => 1));
        $result = $client->buscaEventos($this->getParametros());
        $saida = $client->__getLastResponse();
        $saida = substr($saida, strpos($saida,"return")-1, strlen($saida));
        $saida = substr($saida, 0, -61);
        $resultado = simplexml_load_string($saida);
        if ($resultado instanceof \SimpleXMLElement)

**Comment by ivanwhm** [comment]
Legal pessoal. Obrigado por todas as colaborações. Quero lembrar que este projeto é nosso. Sintam-se a vontade para fazer qualquer tipo de alteração no código-fonte.

**Comment by loja5combr** [comment]
Ola a todos, também não consegui de forma ou maneira usa o mesmo em soap no meu servidor, simplesmente trava e não carrega nenhuma informação de rastreio, com isso tive de fazer uma POG hehehe, segue abaixo, para mim funcionou perfeitamente e bem rápido o carregamento. 

`<?php
function rastrearmento($objetos='',$tipo='T') {
			$url = "http://webservice.correios.com.br/service/rastro";

			$body = '<Envelope xmlns="http://schemas.xmlsoap.org/soap/envelope/">
				<Body>
					<buscaEventos xmlns="http://resource.webservice.correios.com.br/">
						<usuario xmlns="">ECT</usuario>
						<senha xmlns="">SRO</senha>
						<tipo xmlns="">L</tipo>
						<resultado xmlns="">'.$tipo.'</resultado>
						<lingua xmlns="">101</lingua>
						<objetos xmlns="">'.$objetos.'</objetos>
					</buscaEventos>
				</Body>
			</Envelope>';

			$headers = array( 
				'Content-Type: text/xml; charset="utf-8"', 
				'Content-Length: '.strlen($body), 
				'Accept: text/xml', 
				'Cache-Control: no-cache', 
				'Pragma: no-cache', 
				'SOAPAction: "buscaEventos"'
			); 

			$ch = curl_init(); 
			curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
			curl_setopt($ch, CURLOPT_URL, $url); 
			curl_setopt($ch, CURLOPT_RETURNTRANSFER, true); 
			curl_setopt($ch, CURLOPT_TIMEOUT, 60); 
			curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
			curl_setopt($ch, CURLOPT_POST, true); 
			curl_setopt($ch, CURLOPT_POSTFIELDS, $body);

			$curlErrno  = curl_errno($ch);
			$curlErr    = curl_error($ch);
			
			$xml = curl_exec($ch); 
			curl_close($ch);
			
			$xml = preg_replace("/(<\/?)(\w+):([^>]*>)/", "$1$2$3", $xml);
			$xml = simplexml_load_string($xml);
			$json = @json_encode($xml);
			$obj = @json_decode($json,true);
			
			if($curlErrno==0 && isset($obj['soapenvBody']['ns2buscaEventosResponse']['return'])){
			return $obj['soapenvBody']['ns2buscaEventosResponse']['return'];	
			}else{
			return array('error'=>'Problema ao conectar-se ao sistema correios ou servidor fora do ar! Tente novamente.');
			}
}

//exemplo
print_r(rastrearmento('RE798401194SE'));
?>`

**Comment by btrazzini** [comment]
Pessoal com relação ao timeout do SoapClient, basta adicionar no seu script:
`ini_set('default_socket_timeout', 1); `

**Comment by alexisdeza** [comment]
@daviddgm isso que você queria? O retorno já está é um objeto, não precisa transformar a string em um objeto SimpleXMLElement.
` if (@fopen(parent::URL_CALCULADOR, 'r')) {
//Inicia a consulta
//            echo http_build_query($this->getParametros());
//            $curl = curl_init();
//            curl_setopt($curl, CURLOPT_URL, parent::URL_RASTREADOR);
//            curl_setopt($curl, CURLOPT_RETURNTRANSFER, 1);
//            curl_setopt($curl, CURLOPT_POST, 1);
//            curl_setopt($curl, CURLOPT_POSTFIELDS, http_build_query($this->getParametros()));
//            $result = curl_exec($curl);
//            echo $result;
//            $saida = $result;
//            curl_close($curl);
            $client = new \SoapClient(parent::URL_RASTREADOR, array('trace' => 1));
            $result = $client->buscaEventos($this->getParametros());
            if (isset($result->return) and $resultado = $result->return) {
                $retorno = TRUE; `

**Comment by vitorSC** [comment]
Galera, onde conseguiram baixar o Rastro_schema1.xsd?

**Comment by daviddgm** [comment]
Obrigado @alexisdeza 

@vitorSC https://webservice.correios.com.br/service/rastro/Rastro_schema1.xsd

**Comment by vitorSC** [comment]
Valeu, muito obrigado, a pressão tá grande pra arrumar isso aqui na loja \o/

**Comment by frankdors** [comment]
Consegui implementar aqui...

Mais informações:
https://github.com/pedro-teixeira/correios/pull/139#issuecomment-226487209

**Comment by legustas** [comment]
@loja5combr Funciona a function. Só aconselho o uso da funcao: RastroJson. Melhor o retorno.
Alternativa para quem usa CURL ao invés de SOAP.

Retorno bem rápido
