### ISSUE TITLE
Erro ao executar exemplo rastreamento_objeto.php

### ISSUE THREAD

**Issue by guircoelho** [ivanwhm/correios#7]
Olá!

Ao executar o script examples/rastreamento_objeto.php, após alguns minutos, aparece o erro abaixo:

"Ocorreu um erro ao processar sua solicitação. Erro: java.lang.NullPointerException"

Imagino que seja algum problema na API dos Correios. Alguém tem uma solução?

Obrigado!

**Comment by ivanwhm** [comment]
Bom dia,
Este erro está associado ao uso do parâmetro TIPO_RASTREAMENTO_INTERVALO. Por algum motivo que eu desconheço, quando esta opção é usada os Correios retornam este erro.
Aproveitei, fiz um comentário no arquivo sobre o erro e alguns ajustes.
