### ISSUE TITLE
Dúvida sobre rastreamento

### ISSUE THREAD

**Issue by vhenckel** [ivanwhm/correios#8]
Para rastrear encomendas é necessário cadastro junto aos Correios?
Digo isso pois testei e sempre retorna vazio a lista de objetos rastreados.
Se alguém souber me responder, agradeço.
Estou criando um bot gratuito para o Messenger e WhatsApp para enviar mudança de status de encomendas.
Aguardo.

**Comment by ivanwhm** [comment]
Boa tarde,

Tente usar as seguintes informações no usuário e senha:

Usuário: ECT
Senha: SRO
