### ISSUE TITLE
Timeout

### ISSUE THREAD

**Issue by sarment0** [ivanwhm/correios#9]
Estou tentando utilizar este projeto mas está sempre dando erro de timeout, utilizei o exemplo e não funcionou.

Seria algum problema nos correios ou estou fazendo algo de errado? 

504 Gateway Time-out

nginx/1.11.3

**Comment by ivanwhm** [comment]
Boa tarde,
Infelizmente isto começou a ocorrer quando os Correios mudou a URL de rastreamento este ano. Esta nova URL além de ser demorada, muitas vezes provoca timeout no retorno das informações.

Hoje o timeout máximo está definido no arquivo /src/Rastreamento/CorreiosRastreamento.php, método processaConsulta() no item ini_set("default_socket_timeout", 15).

Peço que tente ajustar este timeout até que consiga encontrar a melhor alternativa para o teu caso.
